import Feed from '@components/Feed'
const home = () => {
  return (
     <section className = "w-full flex-center flex-col">
      <h1 className = "head_text text-center">Discover And Share
       <br className = "max-md:hidden" />
       <span className = "orange_gradient text-center">AI - powered prompts</span>
      </h1>  

      <p className = "desc text-center">Promptopia: An AI-powered Next.js app offering curated prompts for creative inspiration. Explore diverse prompts generated by artificial intelligence to spark creativity in various fields effortlessly.</p>

      <Feed/>
     </section>
  )
}

export default home